WITH ULTIMA_DATA AS (
    SELECT IDEMPRESA, MAX(DTMOVIMENTO) AS DTMOVIMENTO
    FROM DBA.ESTOQUE_SALDO_ATUAL
    WHERE IDEMPRESA IN ({{FILIAIS}})
        AND DTMOVIMENTO <= CURRENT DATE
    GROUP BY IDEMPRESA
)
SELECT
    ES.IDEMPRESA,
    PV.IDSUBPRODUTO,
    PV.DESCRICAOPRODUTO,
    PV.IDCODBARPROD,
    CAST(ES.QTDATUALESTOQUE AS NUMERIC(15, 2)) AS QTDATUALESTOQUE,
    CAST(ES.VALATUALESTOQUE AS NUMERIC(15, 2)) AS VALATUALESTOQUE,
    ES.DTULTIMAVENDA
FROM
    DBA.ESTOQUE_SALDO_ATUAL ES
    INNER JOIN ULTIMA_DATA UD ON UD.IDEMPRESA = ES.IDEMPRESA AND UD.DTMOVIMENTO = ES.DTMOVIMENTO
    INNER JOIN DBA.PRODUTOS_VIEW PV ON PV.IDSUBPRODUTO = ES.IDSUBPRODUTO
WHERE
    ES.IDEMPRESA IN ({{FILIAIS}})
    AND ES.QTDATUALESTOQUE > 0
    AND ES.VALATUALESTOQUE > 0
    AND (ES.DTULTIMAVENDA IS NULL OR ES.DTULTIMAVENDA < CURRENT DATE - ? DAYS)
ORDER BY
    ES.VALATUALESTOQUE DESC
FETCH FIRST 50 ROWS ONLY
