SELECT
    EA.IDEMPRESA,
    TRIM(CHAR(YEAR(EA.DTMOVIMENTO))) || '-' || RIGHT('0' || TRIM(CHAR(MONTH(EA.DTMOVIMENTO))), 2) AS MES,
    SUM(EA.VALTOTLIQUIDO) AS FATURAMENTO,
    SUM(EA.VALLUCRO) AS LUCRO
FROM DBA.ESTOQUE_ANALITICO EA
JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
WHERE EA.IDEMPRESA IN ({{FILIAIS}})
  AND OI.TIPOCATEGORIA = 'A'
  AND OI.FLAGCALCULALUCRATIVIDADE = 'T'
  AND OI.IDOPERACAO <> 1089
  AND EA.DTMOVIMENTO >= ?
GROUP BY EA.IDEMPRESA, YEAR(EA.DTMOVIMENTO), MONTH(EA.DTMOVIMENTO)
ORDER BY MES, EA.IDEMPRESA
