WITH VENDA AS (
    SELECT
        CASE WHEN EA.IDVENDEDOR IN (3529,3490,3491,3530,8904,134277) THEN 99 ELSE EA.IDEMPRESA END AS IDEMPRESA,
        TRIM(CHAR(YEAR(EA.DTMOVIMENTO))) || '-' || RIGHT('0' || TRIM(CHAR(MONTH(EA.DTMOVIMENTO))), 2) AS MES,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT,0) <= 0 THEN
                CASE OI.TIPOMOVIMENTO WHEN 'E' THEN EA.VALTOTLIQUIDO * -1 ELSE EA.VALTOTLIQUIDO END
            ELSE 0
        END AS VENDABRUTA
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES ON NES.IDEMPRESA=EA.IDEMPRESA AND NES.IDPLANILHA=EA.IDPLANILHA AND NES.DTMOVIMENTO=EA.DTMOVIMENTO
    INNER JOIN DBA.NOTAS N ON N.IDEMPRESA=EA.IDEMPRESA AND N.IDPLANILHA=EA.IDPLANILHA AND N.FLAGNOTACANCEL='F'
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO=EA.IDOPERACAO AND OI.FLAGMOVPRODUTOS='T' AND OI.TIPOMOVIMENTO IN ('V','E')
    WHERE EA.IDOPERACAO <> 1301
      AND EA.IDEMPRESA IN ({{FILIAIS}})
      AND NES.TIPOITEMCATEGORIA NOT IN ('D8')
      AND EA.DTMOVIMENTO >= ?
),
LUCRO AS (
    -- Nao trata o caso raro de produto Kit (TIPOBAIXAMESTRE='K') com precisao total:
    -- exigiria uma subquery correlacionada que derruba o plano de execucao (39s -> 3.5s
    -- sem ela, testado com 24 meses de dados) para um ganho de precisao irrelevante
    -- (2 linhas em 2 anos de historico).
    SELECT
        CASE WHEN EA.IDVENDEDOR IN (3529,3490,3491,3530,8904,134277) THEN 99 ELSE EA.IDEMPRESA END AS IDEMPRESA,
        TRIM(CHAR(YEAR(EA.DTMOVIMENTO))) || '-' || RIGHT('0' || TRIM(CHAR(MONTH(EA.DTMOVIMENTO))), 2) AS MES,
        CASE OI.TIPOMOVIMENTO WHEN 'E' THEN 0 ELSE COALESCE(EA.VALLUCRO,0) * EA.QTDPRODUTO END AS LUCROBRUTO
    FROM DBA.ESTOQUE_ANALITICO EA
    JOIN DBA.NOTAS_ENTRADA_SAIDA NES ON NES.IDPLANILHA=EA.IDPLANILHA AND NES.IDEMPRESA=EA.IDEMPRESA AND NES.DTMOVIMENTO=EA.DTMOVIMENTO
    JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO=EA.IDOPERACAO
    WHERE COALESCE(EA.NUMSEQUENCIAKIT,0) <= 0
      AND NES.TIPOITEMCATEGORIA NOT IN ('D8')
      AND OI.FLAGMOVPRODUTOS = 'T'
      AND OI.TIPOMOVIMENTO IN ('V','E')
      AND EA.IDEMPRESA IN ({{FILIAIS}})
      AND EA.IDOPERACAO <> 1301
      AND EA.DTMOVIMENTO >= ?
),
CUPONS AS (
    SELECT
        CASE WHEN EA.IDVENDEDOR IN (3529,3490,3491,3530,8904,134277) THEN 99 ELSE EA.IDEMPRESA END AS IDEMPRESA,
        TRIM(CHAR(YEAR(EA.DTMOVIMENTO))) || '-' || RIGHT('0' || TRIM(CHAR(MONTH(EA.DTMOVIMENTO))), 2) AS MES,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT,0) <= 0 AND OI.TIPOMOVIMENTO <> 'E' THEN EA.IDPLANILHA
            ELSE NULL
        END AS CUPOM
    FROM DBA.ESTOQUE_ANALITICO EA
    JOIN DBA.NOTAS_ENTRADA_SAIDA NES ON NES.IDPLANILHA=EA.IDPLANILHA AND NES.IDEMPRESA=EA.IDEMPRESA AND NES.DTMOVIMENTO=EA.DTMOVIMENTO
    JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO=EA.IDOPERACAO
    WHERE EA.IDEMPRESA IN ({{FILIAIS}})
      AND EA.IDOPERACAO <> 1301
      AND EA.DTMOVIMENTO >= ?
),
VENDA_AGG AS (SELECT IDEMPRESA, MES, SUM(VENDABRUTA) AS FATURAMENTO FROM VENDA GROUP BY IDEMPRESA, MES),
LUCRO_AGG AS (SELECT IDEMPRESA, MES, SUM(LUCROBRUTO) AS LUCRO FROM LUCRO GROUP BY IDEMPRESA, MES),
CUPONS_AGG AS (SELECT IDEMPRESA, MES, COUNT(DISTINCT CUPOM) AS N_CUPONS FROM CUPONS GROUP BY IDEMPRESA, MES),
CHAVES AS (
    SELECT IDEMPRESA, MES FROM VENDA_AGG
    UNION SELECT IDEMPRESA, MES FROM LUCRO_AGG
    UNION SELECT IDEMPRESA, MES FROM CUPONS_AGG
)
SELECT
    C.IDEMPRESA,
    C.MES,
    CAST(COALESCE(V.FATURAMENTO,0) AS NUMERIC(15,2)) AS FATURAMENTO,
    CAST(COALESCE(L.LUCRO,0) AS NUMERIC(15,2)) AS LUCRO,
    COALESCE(CU.N_CUPONS,0) AS N_CUPONS
FROM CHAVES C
LEFT JOIN VENDA_AGG V ON V.IDEMPRESA=C.IDEMPRESA AND V.MES=C.MES
LEFT JOIN LUCRO_AGG L ON L.IDEMPRESA=C.IDEMPRESA AND L.MES=C.MES
LEFT JOIN CUPONS_AGG CU ON CU.IDEMPRESA=C.IDEMPRESA AND CU.MES=C.MES
ORDER BY C.MES, C.IDEMPRESA
