WITH ULTIMA_DATA AS (
    SELECT IDEMPRESA, MAX(DTMOVIMENTO) AS DTMOVIMENTO
    FROM DBA.ESTOQUE_SALDO_ATUAL
    WHERE IDEMPRESA IN ({{FILIAIS}})
        AND DTMOVIMENTO <= CURRENT DATE
    GROUP BY IDEMPRESA
),
ESTOQUE AS (
    SELECT
        ES.IDEMPRESA,
        ES.QTDATUALESTOQUE,
        ES.VALATUALESTOQUE,
        ES.DTULTIMAVENDA
    FROM
        DBA.ESTOQUE_SALDO_ATUAL ES
        INNER JOIN ULTIMA_DATA UD ON UD.IDEMPRESA = ES.IDEMPRESA AND UD.DTMOVIMENTO = ES.DTMOVIMENTO
    WHERE
        ES.IDSUBPRODUTO = ?
),
PRECO AS (
    SELECT
        TPP.IDEMPRESA,
        TPP.VALPRECOVENDA
    FROM
        DBA.TABELA_PRECO_PRODUTO TPP
    WHERE
        TPP.IDSUBPRODUTO = ?
        AND TPP.IDTABELAPRECO = 1
        AND TPP.IDEMPRESA IN ({{FILIAIS}})
)
SELECT
    E.IDEMPRESA,
    E.QTDATUALESTOQUE,
    E.VALATUALESTOQUE,
    P.VALPRECOVENDA,
    E.DTULTIMAVENDA
FROM
    ESTOQUE E
    LEFT JOIN PRECO P ON P.IDEMPRESA = E.IDEMPRESA

UNION

SELECT
    P.IDEMPRESA,
    E.QTDATUALESTOQUE,
    E.VALATUALESTOQUE,
    P.VALPRECOVENDA,
    E.DTULTIMAVENDA
FROM
    PRECO P
    LEFT JOIN ESTOQUE E ON E.IDEMPRESA = P.IDEMPRESA
WHERE
    E.IDEMPRESA IS NULL
ORDER BY
    1
