SELECT
    EA.IDEMPRESA,
    CAST(SUM(CASE WHEN OI.TIPOMOVIMENTO = 'V' THEN EA.VALTOTLIQUIDO ELSE 0 END) AS NUMERIC(15, 2)) AS VENDA,
    CAST(SUM(CASE WHEN OI.TIPOMOVIMENTO = 'V' THEN COALESCE(EA.VALLUCRO, 0) * EA.QTDPRODUTO ELSE 0 END) AS NUMERIC(15, 2)) AS LUCRO,
    CAST(SUM(CASE WHEN OI.TIPOMOVIMENTO = 'V' THEN EA.QTDPRODUTO ELSE 0 END) AS NUMERIC(15, 2)) AS QTD_VENDIDA
FROM
    DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
WHERE
    EA.IDSUBPRODUTO = ?
    AND OI.FLAGMOVPRODUTOS = 'T'
    AND OI.TIPOMOVIMENTO = 'V'
    AND EA.IDEMPRESA IN ({{FILIAIS}})
    AND EA.DTMOVIMENTO BETWEEN ? AND ?
GROUP BY
    EA.IDEMPRESA
ORDER BY
    EA.IDEMPRESA
