SELECT
    PV.IDSUBPRODUTO,
    PV.DESCRICAOPRODUTO,
    PV.FABRICANTE,
    PV.IDCODBARPROD,
    PV.EMBALAGEMSAIDA,
    PV.PESOLIQUIDO,
    D.DESCRDIVISAO,
    S.DESCRSECAO,
    G.DESCRGRUPO,
    SG.DESCRSUBGRUPO
FROM
    DBA.PRODUTOS_VIEW PV
    LEFT JOIN DBA.DIVISAO D ON D.IDDIVISAO = PV.IDDIVISAO
    LEFT JOIN DBA.SECAO S ON S.IDSECAO = PV.IDSECAO
    LEFT JOIN DBA.GRUPO G ON G.IDGRUPO = PV.IDGRUPO
    LEFT JOIN DBA.SUBGRUPO SG ON SG.IDSUBGRUPO = PV.IDSUBGRUPO
WHERE
    PV.IDSUBPRODUTO = ?
