SELECT
    PV.IDSUBPRODUTO,
    PV.DESCRICAOPRODUTO,
    PV.IDCODBARPROD,
    S.DESCRSECAO
FROM
    DBA.PRODUTOS_VIEW PV
    LEFT JOIN DBA.SECAO S ON S.IDSECAO = PV.IDSECAO
WHERE
    PV.FLAGINATIVO = 'F'
    AND (
        UPPER(PV.DESCRICAOPRODUTO) LIKE UPPER(?)
        OR CAST(PV.IDSUBPRODUTO AS VARCHAR(20)) LIKE ?
        OR CAST(PV.IDCODBARPROD AS VARCHAR(20)) LIKE ?
    )
ORDER BY
    PV.DESCRICAOPRODUTO
FETCH FIRST 50 ROWS ONLY
