SELECT
    PG.IDPROMOCAO,
    PG.DESCRPROMOCAO,
    PG.DTINIPROMOCAO,
    PG.DTFIMPROMOCAO,
    (
        SELECT COUNT(*)
        FROM DBA.PROMOCAO_GESTAO_PRODUTO PGP
        WHERE PGP.IDPROMOCAO = PG.IDPROMOCAO AND PGP.FLAGINATIVO = 'F'
    ) AS QTD_PRODUTOS,
    (
        SELECT COUNT(*)
        FROM DBA.PROMOCAO_GESTAO_EMPRESA PGE2
        WHERE PGE2.IDPROMOCAO = PG.IDPROMOCAO AND PGE2.FLAGINATIVO = 'F'
    ) AS QTD_LOJAS
FROM
    DBA.PROMOCAO_GESTAO PG
WHERE
    PG.FLAGINATIVO = 'F'
    AND PG.DTFIMPROMOCAO >= ?
    AND PG.DTINIPROMOCAO <= ?
    AND EXISTS (
        SELECT 1
        FROM DBA.PROMOCAO_GESTAO_EMPRESA PGE
        WHERE PGE.IDPROMOCAO = PG.IDPROMOCAO
            AND PGE.FLAGINATIVO = 'F'
            AND PGE.IDEMPRESA IN ({{FILIAIS}})
    )
ORDER BY
    PG.DTINIPROMOCAO DESC
