SELECT
    PGP.IDSUBPRODUTO,
    CAST(COALESCE(SUM(CASE WHEN OI.TIPOMOVIMENTO = 'V' THEN EA.VALTOTLIQUIDO ELSE 0 END), 0) AS NUMERIC(15, 2)) AS VENDA,
    CAST(COALESCE(SUM(CASE WHEN OI.TIPOMOVIMENTO = 'V' THEN COALESCE(EA.VALLUCRO, 0) * EA.QTDPRODUTO ELSE 0 END), 0) AS NUMERIC(15, 2)) AS LUCRO,
    CAST(COALESCE(SUM(CASE WHEN OI.TIPOMOVIMENTO = 'V' THEN EA.QTDPRODUTO ELSE 0 END), 0) AS NUMERIC(15, 2)) AS QTD_VENDIDA
FROM
    DBA.PROMOCAO_GESTAO_PRODUTO PGP
    LEFT JOIN DBA.ESTOQUE_ANALITICO EA
        ON EA.IDSUBPRODUTO = PGP.IDSUBPRODUTO
        AND EA.IDEMPRESA IN ({{FILIAIS}})
        AND EA.DTMOVIMENTO BETWEEN ? AND ?
    LEFT JOIN DBA.OPERACAO_INTERNA OI
        ON OI.IDOPERACAO = EA.IDOPERACAO
        AND OI.FLAGMOVPRODUTOS = 'T'
WHERE
    PGP.IDPROMOCAO = ?
    AND PGP.FLAGINATIVO = 'F'
GROUP BY
    PGP.IDSUBPRODUTO
