SELECT
    PGP.IDSUBPRODUTO,
    PV.DESCRICAOPRODUTO,
    PV.IDCODBARPROD,
    CAST(PGP.VALPRECO AS NUMERIC(15, 2)) AS VALPRECO,
    CAST(COALESCE(PGP.VALDESCONTO, 0) AS NUMERIC(15, 2)) AS VALDESCONTO,
    CAST(COALESCE(PGP.PERDESCONTO, 0) AS NUMERIC(6, 2)) AS PERDESCONTO
FROM
    DBA.PROMOCAO_GESTAO_PRODUTO PGP
    INNER JOIN DBA.PRODUTOS_VIEW PV ON PV.IDSUBPRODUTO = PGP.IDSUBPRODUTO
WHERE
    PGP.IDPROMOCAO = ?
    AND PGP.FLAGINATIVO = 'F'
ORDER BY
    PV.DESCRICAOPRODUTO
