SELECT
    P.DESCRCOMPRODUTO AS PRODUTO,
    SUM(EA.VALTOTLIQUIDO) AS FATURAMENTO,
    SUM(EA.QTDPRODUTO) AS QUANTIDADE,
    SUM(EA.VALLUCRO) AS LUCRO,
    COUNT(DISTINCT EA.IDEMPRESA || '-' || EA.IDPLANILHA) AS NRO_CUPONS
FROM DBA.ESTOQUE_ANALITICO EA
JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
JOIN DBA.PRODUTO P ON P.IDPRODUTO = EA.IDPRODUTO
WHERE EA.IDEMPRESA IN ({{FILIAIS}})
  AND OI.TIPOCATEGORIA = 'A'
  AND OI.FLAGCALCULALUCRATIVIDADE = 'T'
  AND OI.IDOPERACAO <> 1089
  AND EA.DTMOVIMENTO >= ?
  AND EA.DTMOVIMENTO < ?
GROUP BY P.DESCRCOMPRODUTO
ORDER BY FATURAMENTO DESC
FETCH FIRST 200 ROWS ONLY
