WITH VENDA AS (
    SELECT
        EA.IDPRODUTO,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT,0) <= 0 THEN
                CASE OI.TIPOMOVIMENTO WHEN 'E' THEN EA.VALTOTLIQUIDO * -1 ELSE EA.VALTOTLIQUIDO END
            ELSE 0
        END AS VENDABRUTA,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT,0) <= 0 THEN
                CASE OI.TIPOMOVIMENTO WHEN 'E' THEN EA.QTDPRODUTO * -1 ELSE EA.QTDPRODUTO END
            ELSE 0
        END AS QTD
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES ON NES.IDEMPRESA=EA.IDEMPRESA AND NES.IDPLANILHA=EA.IDPLANILHA AND NES.DTMOVIMENTO=EA.DTMOVIMENTO
    INNER JOIN DBA.NOTAS N ON N.IDEMPRESA=EA.IDEMPRESA AND N.IDPLANILHA=EA.IDPLANILHA AND N.FLAGNOTACANCEL='F'
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO=EA.IDOPERACAO AND OI.FLAGMOVPRODUTOS='T' AND OI.TIPOMOVIMENTO IN ('V','E')
    WHERE EA.IDOPERACAO <> 1301
      AND EA.IDEMPRESA IN ({{FILIAIS}})
      AND NES.TIPOITEMCATEGORIA NOT IN ('D8')
      AND EA.DTMOVIMENTO >= ? AND EA.DTMOVIMENTO < ?
),
LUCRO AS (
    SELECT
        EA.IDPRODUTO,
        CASE OI.TIPOMOVIMENTO WHEN 'E' THEN 0 ELSE COALESCE(EA.VALLUCRO,0) * EA.QTDPRODUTO END AS LUCROBRUTO
    FROM DBA.ESTOQUE_ANALITICO EA
    JOIN DBA.NOTAS_ENTRADA_SAIDA NES ON NES.IDPLANILHA=EA.IDPLANILHA AND NES.IDEMPRESA=EA.IDEMPRESA AND NES.DTMOVIMENTO=EA.DTMOVIMENTO
    JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO=EA.IDOPERACAO
    WHERE COALESCE(EA.NUMSEQUENCIAKIT,0) <= 0
      AND NES.TIPOITEMCATEGORIA NOT IN ('D8')
      AND OI.FLAGMOVPRODUTOS = 'T'
      AND OI.TIPOMOVIMENTO IN ('V','E')
      AND EA.IDEMPRESA IN ({{FILIAIS}})
      AND EA.IDOPERACAO <> 1301
      AND EA.DTMOVIMENTO >= ? AND EA.DTMOVIMENTO < ?
),
CUPONS AS (
    SELECT
        EA.IDPRODUTO,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT,0) <= 0 AND OI.TIPOMOVIMENTO <> 'E' THEN EA.IDEMPRESA * 100000000 + EA.IDPLANILHA
            ELSE NULL
        END AS CUPOM
    FROM DBA.ESTOQUE_ANALITICO EA
    JOIN DBA.NOTAS_ENTRADA_SAIDA NES ON NES.IDPLANILHA=EA.IDPLANILHA AND NES.IDEMPRESA=EA.IDEMPRESA AND NES.DTMOVIMENTO=EA.DTMOVIMENTO
    JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO=EA.IDOPERACAO
    WHERE EA.IDEMPRESA IN ({{FILIAIS}})
      AND EA.IDOPERACAO <> 1301
      AND EA.DTMOVIMENTO >= ? AND EA.DTMOVIMENTO < ?
),
VENDA_AGG AS (SELECT IDPRODUTO, SUM(VENDABRUTA) AS FATURAMENTO, SUM(QTD) AS QUANTIDADE FROM VENDA GROUP BY IDPRODUTO),
LUCRO_AGG AS (SELECT IDPRODUTO, SUM(LUCROBRUTO) AS LUCRO FROM LUCRO GROUP BY IDPRODUTO),
CUPONS_AGG AS (SELECT IDPRODUTO, COUNT(DISTINCT CUPOM) AS NRO_CUPONS FROM CUPONS GROUP BY IDPRODUTO)
SELECT
    P.DESCRCOMPRODUTO AS PRODUTO,
    CAST(COALESCE(V.FATURAMENTO,0) AS NUMERIC(15,2)) AS FATURAMENTO,
    CAST(COALESCE(V.QUANTIDADE,0) AS NUMERIC(15,2)) AS QUANTIDADE,
    CAST(COALESCE(L.LUCRO,0) AS NUMERIC(15,2)) AS LUCRO,
    COALESCE(CU.NRO_CUPONS,0) AS NRO_CUPONS
FROM VENDA_AGG V
INNER JOIN DBA.PRODUTO P ON P.IDPRODUTO = V.IDPRODUTO
LEFT JOIN LUCRO_AGG L ON L.IDPRODUTO = V.IDPRODUTO
LEFT JOIN CUPONS_AGG CU ON CU.IDPRODUTO = V.IDPRODUTO
WHERE V.FATURAMENTO <> 0 OR V.QUANTIDADE <> 0
ORDER BY FATURAMENTO DESC
FETCH FIRST 200 ROWS ONLY
