WITH ENVIADO AS (
    SELECT EA.IDEMPRESA, SUM(EA.QTDPRODUTO) AS QTD, SUM(EA.VALTOTLIQUIDO) AS VALOR
    FROM DBA.ESTOQUE_ANALITICO EA
    WHERE EA.IDOPERACAO = 1106
        AND EA.IDEMPRESA IN ({{FILIAIS}})
        AND EA.DTMOVIMENTO BETWEEN ? AND ?
    GROUP BY EA.IDEMPRESA
),
RECEBIDO AS (
    SELECT EA.IDEMPRESA, SUM(EA.QTDPRODUTO) AS QTD, SUM(EA.VALTOTLIQUIDO) AS VALOR
    FROM DBA.ESTOQUE_ANALITICO EA
    WHERE EA.IDOPERACAO = 106
        AND EA.IDEMPRESA IN ({{FILIAIS}})
        AND EA.DTMOVIMENTO BETWEEN ? AND ?
    GROUP BY EA.IDEMPRESA
)
SELECT
    E.IDEMPRESA,
    CAST(COALESCE(ENV.VALOR, 0) AS NUMERIC(15, 2)) AS VALOR_ENVIADO,
    CAST(COALESCE(REC.VALOR, 0) AS NUMERIC(15, 2)) AS VALOR_RECEBIDO
FROM (
    SELECT IDEMPRESA FROM ENVIADO
    UNION
    SELECT IDEMPRESA FROM RECEBIDO
) E
    LEFT JOIN ENVIADO ENV ON ENV.IDEMPRESA = E.IDEMPRESA
    LEFT JOIN RECEBIDO REC ON REC.IDEMPRESA = E.IDEMPRESA
ORDER BY
    E.IDEMPRESA
