SELECT
    NV.IDEMPRESA,
    NV.IDPLANILHA,
    PV.IDSUBPRODUTO,
    PV.DESCRICAOPRODUTO,
    PV.IDCODBARPROD,
    NES.DTMOVIMENTO AS DTLANCAMENTO,
    NV.DTVALIDADE,
    CAST(NV.QTDPRODUTO AS NUMERIC(12, 2)) AS QTDPRODUTO,
    CAST(NV.QTDPRODUTO * COALESCE(TPP.VALPRECOVENDA, 0) AS NUMERIC(15, 2)) AS VALOR_ESTIMADO
FROM
    DBA.NOTAS_VALIDADE NV
    INNER JOIN DBA.PRODUTOS_VIEW PV ON PV.IDSUBPRODUTO = NV.IDSUBPRODUTO
    LEFT JOIN DBA.NOTAS_ENTRADA_SAIDA NES ON NES.IDEMPRESA = NV.IDEMPRESA AND NES.IDPLANILHA = NV.IDPLANILHA
    LEFT JOIN DBA.TABELA_PRECO_PRODUTO TPP
        ON TPP.IDSUBPRODUTO = NV.IDSUBPRODUTO
        AND TPP.IDEMPRESA = NV.IDEMPRESA
        AND TPP.IDTABELAPRECO = 1
WHERE
    NV.IDEMPRESA IN ({{FILIAIS}})
    AND NV.DTVALIDADE >= CURRENT DATE
    AND NV.DTVALIDADE <= CURRENT DATE + ? DAYS
ORDER BY
    NV.DTVALIDADE ASC
FETCH FIRST 300 ROWS ONLY
